server:
  hostname: localhost
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/financetracker
    username: postgres
    password: password
    initialization-mode: always  # Set to none when not in development

