server:
  hostname: localhost
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.1.10:5432/survey
    username: postgres
    password: postgres
    initialization-mode: always  # Set to none when not in development

